# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Elixir Automation
email: abhilash04sharma@gmail.com
description: Test Automation Framework Development.
baseurl: "/ElixirAutomation" # the subpath of your site, e.g. /blog

# Social settings
500px_url: 
facebook_url: https://www.facebook.com/abhilash.sharma.5496
github_url: https://github.com/Abhilash04
gitlab_url: 
googleplus_url: https://plus.google.com/+AbhilashSharmaIR
instagram_url: https://www.instagram.com/abhi_sharma4/
linkedin_url: https://www.linkedin.com/in/abhilash-sharma-b8444b51/
pinterest_url: 
slack_url: 
twitter_url: https://twitter.com/abhi_cognite

# Build settings
markdown: kramdown

# Plugin: jekyll-seo-tag
twitter:
  username: andrewbanchich
# Add one or more of the following
facebook:
  app_id: 
  publisher: 
  admins: 
logo:
google_site_verification:
